Prototype/Models/Book.cs
using System.ComponentModel.DataAnnotations;

namespace Prototype.Models
{
    public class Book
    {
        [Key]
        public int ID { get; set; }

        public string ISBN { get; set; }

        public string Name { get; set; }

        public string Author { get; set; }

        public string Publisher { get; set; }

        public string Description { get; set; }

        public string Genre { get; set; }

        public string PdfName { get; set; }
    }
}

Prototype/Models/ErrorViewModel.cs
using System;

namespace Prototype.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Prototype/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using Prototype.Data;
using System.Collections.Generic;
using System.Linq;
using Prototype.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;

namespace Prototype.Controllers
{
    [Authorize]
    public class BookController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly ModelFactory modelFactory;
        private IEnumerable<string> Pages;

        public BookController(ApplicationDbContext db)
        {
            _db = db;
            modelFactory = new ModelFactory(_db);
        }

        public IActionResult Index(int id)
        {
            Pages = modelFactory.GetPages(id);
            HttpContext.Session.SetString("Pages", JsonConvert.SerializeObject(Pages));
            HttpContext.Session.SetString("PageNumber", "0");

            return RedirectToAction("read");
        }

        public IActionResult Read()
        {
            Pages = JsonConvert.DeserializeObject<IEnumerable<string>>(HttpContext.Session.GetString("Pages"));
            int pageNum = int.Parse(HttpContext.Session.GetString("PageNumber"));

            if (pageNum > -1)
            {
                if (pageNum > Pages.Count())
                {
                    ViewBag.book = Pages.Last();
                }

                ViewBag.book = Pages.ElementAt(pageNum);
            }
            else
            {
                ViewBag.book = Pages.ElementAt(0);
                HttpContext.Session.SetString("PageNumber", "0");
            }

            return View();
        }

        public IActionResult Listen(int id)
        {
            string path = modelFactory.GetPath(id, false);

            ViewBag.path = path;
            ViewBag.BookName = modelFactory.GetBook(id).Name;

            return View();
        }

        public IActionResult Next()
        {
            int pageNum = int.Parse(HttpContext.Session.GetString("PageNumber"));

            HttpContext.Session.SetString("PageNumber", $"{pageNum + 1}");

            return RedirectToAction("read");
        }

        public IActionResult Previous()
        {
            int pageNum = int.Parse(HttpContext.Session.GetString("PageNumber"));

            HttpContext.Session.SetString("PageNumber", $"{pageNum - 1}");

            return RedirectToAction("read");
        }
    }
}

Prototype/Controllers/CatalogController.cs
using Microsoft.AspNetCore.Mvc;
using Prototype.Data;
using Prototype.Models;
using System.Collections.Generic;
using System.Linq;

namespace Prototype.Controllers
{
    public class CatalogController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly ModelFactory modelFactory;

        public CatalogController(ApplicationDbContext db)
        {
            _db = db;
            modelFactory = new ModelFactory(_db);
        }

        public IActionResult Index(string searching)
        {
            return View(modelFactory.GetBooks(searching));
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Book obj)
        {
            if (obj == null)
            {
                return BadRequest("Given book doesn't have enough information.");
            }

            modelFactory.AddBook(obj);

            return RedirectToAction("Success", obj);
        }

        public IActionResult Success(Book obj)
        {
            return View(obj);
        }

        public IActionResult Detail(int id)
        {
            return View(modelFactory.GetBook(id));
        }
    }
}

Prototype/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Prototype.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Prototype.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Prototype/Views/Book/Listen.cshtml
@{
    ViewData["Title"] = "Listen";
    var path = @ViewBag.path + ".mp3";
    var pathOgg = @ViewBag.path + ".ogg";
}

<h1>Listen to the Book: @ViewBag.BookName</h1>

<div>
    <audio controls>
        <source src="@pathOgg" type="audio/ogg" />
        <source src="@path" type="audio/mpeg" />
    </audio>

</div>

Prototype/Views/Book/Read.cshtml
@model Prototype.Models.Book

@{
    ViewData["Title"] = "Read";
}

<h1>@Html.DisplayFor(model => model.Name)</h1>

<style>
    .highlighted {
        color:red;
        background-color: yellow;
        display: inline;
    }
</style>

<script>
    var spanStack = [];


    function reverseColors() {
        var body = $("body")[0];
        var text = $("#page-text");

        body.classList.toggle("bg-dark");
        text.classList.toggle("text-light");

        var colorButton = $(".color-reverse")[0];

        colorButton.classList.toggle("btn-dark")
        if (colorButton.textContent === "Dark Mode")
        {
            colorButton.textContent = "Light Mode";
        } else
        {
            colorButton.textContent = "Dark Mode";
        }
    }


    function highlightSelection() {
        var userSelection = window.getSelection();
        for(var i = 0; i < userSelection.rangeCount; i++) {
            highlightRange(userSelection.getRangeAt(i));
        }
    }


    function highlightRange(range) {
        var newNode = document.createElement("span");
        newNode.classList.add("highlighted");
        range.surroundContents(newNode);
        spanStack.push(newNode);
    }
    

    function removeLastHighlight() {
        var span = spanStack.pop();
        var text = span.textContent;
        span.parentNode.replaceChild(document.createTextNode(text), span);
    }

    
    function boyutlandir(multiplier) { 
        var c = document.getElementById("page-text");
        if (c.style.fontSize == "") {
            c.style.fontSize = "1.0em";
        } 
        c.style.fontSize = parseFloat(c.style.fontSize) + (multiplier * 0.2) + "em";
    } 
</script>

<button class="color-reverse btn btn-dark btn-light" onclick="reverseColors()">Dark Mode</button>
<button class="btn btn-warning" onclick="highlightSelection()">Highlight</button>
<button class="btn btn-danger" onclick="removeLastHighlight()">Remove Last Highlight</button>
<hr />
<p id="page-text"> <span style="white-space: pre-line"> @ViewBag.book </span></p>

<div class="row justify-content-between">
    <div>
        <a asp-action="Previous" asp-controller="Book" class="btn btn-primary">Previous Page</a> |
        <a asp-action="Next" asp-controller="Book" class="btn btn-primary">Next Page</a> |
    </div>

    <div class="justify-content-end">
        <button onclick="boyutlandir(-1)" class="btn btn-info">Küçült</button> | 
        <button onclick="boyutlandir(1)" class="btn btn-info">Büyüt</button>
    </div>  
</div>
        

Prototype/Views/Catalog/Create.cshtml
@model Prototype.Models.Book

@{
    ViewData["Title"] = "Create";
}
<h1>Create</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ISBN" class="control-label"></label>
                <input asp-for="ISBN" class="form-control" />
                <span asp-validation-for="ISBN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Publisher" class="control-label"></label>
                <input asp-for="Publisher" class="form-control" />
                <span asp-validation-for="Publisher" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PdfName" class="control-label"></label>
                <input asp-for="PdfName" class="form-control" />
                <span asp-validation-for="PdfName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" id="submit" />
            </div>
        </form>
    </div>
</div>



<div>
    <a asp-action="Index">Back to List</a>
</div>

Prototype/Views/Catalog/Detail.cshtml
@model Prototype.Models.Book

@{
    ViewData["Title"] = "Detail";
}

<h1>Detail</h1>

<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ISBN)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Publisher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Publisher)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID" class="btn btn-success">Edit</a> |
    <a asp-action="Index" asp-controller="Book" asp-route-id="@Model.ID" class="btn btn-primary">Read the book</a> |
    <a asp-action="Listen" asp-controller="Book" asp-route-id="@Model.ID" class="btn btn-primary">Listen to the book</a> |
    <a asp-action="Index" class="btn btn-primary">Back to List</a>
</div>

Prototype/Views/Catalog/Index.cshtml
@model IEnumerable<Prototype.Models.Book>
@{
    ViewData["Title"] = "Index";
}

@using(Html.BeginForm("Index", "Catalog", FormMethod.Get))
{
    <div class="input-group mb-3">
        @Html.TextBox("searching")
        <input type="submit" value="search" class="ml-2 btn btn-primary" />
    </div>
}

<div class="container p-3">
    <div class="row pt-4 ">
        <div class="col-6">
            <h2 class="text-primary">Book list</h2>
        </div>
        <div class="col-6">
            <a asp-area="" asp-controller="Catalog" asp-action="Create" class="btn btn-primary float-right">Add new book</a>
        </div>
    </div>
    <br />

    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th class="col-4">Book Name</th>
                <th class="col-4">Publisher</th>
                <th class="col-4">Author</th>
            </tr>
        </thead>
        <tbody>
            @foreach  (var book in Model)
            {
                <tr>
                    <td class="col-4"><a asp-controller="Catalog" asp-action="Detail" asp-route-id="@book.ID">@book.Name</a></td>
                    <td class="col-4">@book.Publisher</td>
                    <td class="col-4">@book.Author</td>
                </tr> 
            }
        </tbody>
    </table>
    
</div>

Prototype/Views/Catalog/Success.cshtml
@model Prototype.Models.Book

@{
    ViewData["Title"] = "Success";
}

<h1>Success</h1>

<h3>You have successfully added the book below into the system.</h3>
<br />
<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ISBN)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Prototype/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to our E-Book Application</h1>
    <p>You have to register or login to the system before reading any books.</a>.</p>
</div>

Prototype/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Prototype</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Prototype</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li><li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catalog" asp-action="Index">Catalog</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Prototype - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>